version: "3"

services:
  registry:
    image: registry:2
    ports:
      - 5000:5000
    volumes:
      - /var/lib/registry:/var/lib/registry
    deploy:
      replicas: 1
      update_config:
        parallelism: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == manager]
  web:
    image: 192.168.99.100:5000/web
    ports:
      - 80:3000
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
      placement:
        constraints: [node.role == worker]
  visualizer:
    image: dockersamples/visualizer:stable
    ports:
      - "8080:8080"
    stop_grace_period: 1m30s
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
    deploy:
      placement:
        constraints: [node.role == manager]
