version: "3"

services:
  web:
    image: registry:5000/web
    ports:
      - 80:3000
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
  api:
    image: registry:5000/api
    ports:
      - 81:4000
    deploy:
      replicas: 3
      update_config:
        parallelism: 1
        delay: 2s
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - node.role == worker
  # couchbase-master:
  #   image: registry.service:5000/couchbase
  #   ports:
  #     - 8091:8091
  #   networks:
  #     couchbase:
  #       aliases:
  #         - master.couchbase
  #   environment:
  #     TYPE: MASTER
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.role == worker
  # couchbase-worker:
  #   image: registry.service:5000/couchbase
  #   networks:
  #     - couchbase
  #   environment:
  #     TYPE: WORKER
  #     COUCHBASE_MASTER: master.couchbase
  #     AUTO_REBALANCE: "false"
  #   deploy:
  #     replicas: 1
  #     placement:
  #       constraints:
  #         - node.role == worker
  #
# networks:
#   couchbase:
