version: "3"

services:
  couchbase-master:
    image: registry.service:5000/couchbase
    ports:
      - 8091:8091
    networks:
      couchbase:
        aliases:
          - master.couchbase
    environment:
      TYPE: MASTER
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker
  couchbase-worker:
    image: registry.service:5000/couchbase
    networks:
      - couchbase
    environment:
      TYPE: WORKER
      COUCHBASE_MASTER: master.couchbase
      AUTO_REBALANCE: "false"
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == worker

networks:
  couchbase:
